DROP TABLE IF EXISTS books;

CREATE TABLE books (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255),
    author VARCHAR(255),
    isbn VARCHAR(255),
    image_url VARCHAR(255),
    book_description TEXT
);

INSERT INTO books (title, author, isbn, image_url, book_description) VALUES
('Master and Commander (Vol. Book 1)', 'Patrick O''Brian', '9780393058956', 'http://books.google.com/books/content?id=HaEdbjUalUEC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'The beginning of the sweeping Aubrey-Maturin series. \"The best sea story I have ever read.\"—Sir Francis Chichester This, the first in the splendid series of Jack Aubrey novels, establishes the friendship between Captain Aubrey, R.N., and Stephen Maturin, ship''s surgeon and intelligence agent, against a thrilling backdrop of the Napoleonic wars. Details of a life aboard a man-of-war in Nelson''s navy are faultlessly rendered: the conversational idiom of the officers in the ward room and the men on the lower deck, the food, the floggings, the mysteries of the wind and the rigging, and the roar of broadsides as the great ships close in battle.'),

('Code', 'Charles Petzold', '9780735638723', 'http://books.google.com/books/content?id=iptCAwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'What do flashlights, the British invasion, black cats, and seesaws have to do with computers? In CODE, they show us the ingenious ways we manipulate language and invent new means of communicating with each other. And through CODE, we see how this ingenuity and our very human compulsion to communicate have driven the technological innovations of the past two centuries. Using everyday objects and familiar language systems such as Braille and Morse code, author Charles Petzold weaves an illuminating narrative for anyone who’s ever wondered about the secret inner life of computers and other smart machines. It’s a cleverly illustrated and eminently comprehensible story—and along the way, you’ll discover you’ve gained a real context for understanding today’s world of PCs, digital media, and the Internet. No matter what your level of technical savvy, CODE will charm you—and perhaps even awaken the technophile within.'),

('On Basilisk Station', 'David Weber', '9781618241214', 'http://books.google.com/books/content?id=uH10CwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'INTRODUCING HONOR HARRINGTON Having made him look a fool, she''s been exiled to Basilisk Station in disgrace and set up for ruin by a superior who hates her. Her demoralized crew blames her for their ship''s humiliating posting to an out-of-the-way picket station. The aborigines of the system''s only habitable planet are smoking homicide-inducing hallucinogens. Parliament isn''t sure it wants to keep the place; the major local industry is smuggling; the merchant cartels want her head; the star-conquering, so-called \"Republic\" of Haven is Up To Something; and Honor Harrington has a single, over-age light cruiser with an armament that doesn''t work to police the entire star system. But the people out to get her have made one mistake. They''ve made her mad. At the publisher''s request, this title is sold without DRM (Digital Rights Management).'),

('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', '9780060531041', 'http://books.google.com/books/content?id=pgPWOaOctq8C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'One of the 20th century''s enduring works, One Hundred Years of Solitude is a widely beloved and acclaimed novel known throughout the world, and the ultimate achievement in a Nobel Prize–winning career. The novel tells the story of the rise and fall of the mythical town of Macondo through the history of the Buendía family. It is a rich and brilliant chronicle of life and death, and the tragicomedy of humankind. In the noble, ridiculous, beautiful, and tawdry story of the Buendía family, one sees all of humanity, just as in the history, myths, growth, and decay of Macondo, one sees all of Latin America. Love and lust, war and revolution, riches and poverty, youth and senility -- the variety of life, the endlessness of death, the search for peace and truth -- these universal themes dominate the novel. Whether he is describing an affair of passion or the voracity of capitalism and the corruption of government, Gabriel García Márquez always writes with the simplicity, ease, and purity that are the mark of a master. Alternately reverential and comical, One Hundred Years of Solitude weaves the political, personal, and spiritual to bring a new consciousness to storytelling. Translated into dozens of languages, this stunning work is no less than an accounting of the history of the human race.'),

('The Disappearing Spoon', 'Sam Kean', '9780316388252', 'http://books.google.com/books/content?id=QBEtDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api', 'A young readers edition of the New York Times bestseller The Disappearing Spoon, chronicling the extraordinary stories behind one of the greatest scientific tools in existence: the periodic table. Why did Gandhi hate iodine (I, 53)? How did radium (Ra, 88) nearly ruin Marie Curie''s reputation? And why did tellurium (Te, 52) lead to the most bizarre gold rush in history? The periodic table is a crowning scientific achievement, but it''s also a treasure trove of adventure, greed, betrayal, and obsession. The fascinating tales in The Disappearing Spoon follow elements on the table as they play out their parts in human history, finance, mythology, conflict, the arts, medicine, and the lives of the (frequently) mad scientists who discovered them. Adapted for a middle grade audience, the young readers edition of The Disappearing Spoon offers the material in a simple, easy-to-follow format, with approximately 20 line drawings and sidebars throughout. Students, teachers, and burgeoning science buffs will love learning about the history behind the chemistry.');